title: Ask Me to Mow
name: Ask Me to Mow
markdown: kramdown
permalink: /:title


# Build settings
plugins:
  - jekyll-feed


# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: webcodehelp
# github_username:  webcodehelp
